# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PPRAfJhg7UW_7tir8oZEWUf72KA99Gb6
"""

x=5
print(f"變數x的值是:{x}")
print(f"變數x的記憶體位置是:{id(x)}")